name: OpenAPI Lint

on:
  pull_request:
    paths:
      - 'docs/api/**/openapi.json'
  push:
    branches: [ main ]
    paths:
      - 'docs/api/**/openapi.json'

jobs:
  spectral-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Spectral
        run: |
          npm -g list @stoplight/spectral-cli || npm -g install @stoplight/spectral-cli

      - name: Lint OpenAPI (core)
        run: |
          spectral lint docs/api/core/openapi.json --fail-severity=warn
